# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author_name', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('post_date', models.DateField(verbose_name='Date posted')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_nickname', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(verbose_name='Date posted')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Blog')),
            ],
        ),
    ]
